package mx.unadm.dpo1;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;

import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame {
    /* Variables globales */
    int _x;
    int _y;
    List<Autor> autores = new ArrayList<Autor>();
    String[] organizaciones = {};
    DefaultTableModel tblModelAutor;
    DefaultTableModel tblModelOrg;
    
    public MainFrame() {
        this.setUndecorated(true);
        initComponents();
        tblModelAutor = (DefaultTableModel)tblAutores.getModel();
        tblModelOrg = (DefaultTableModel)tblOrganizaciones.getModel();
        this.txtOrganizacion.setVisible(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(251, 242, 212));
        setFechaConsultaHoy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnioPublicacion = new javax.swing.JTextField();
        txtDiaPublicacion = new javax.swing.JTextField();
        txtMesPublicacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chkFechaDesconocida = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtOrganizacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAutorIniciales = new javax.swing.JTextField();
        lblAutores = new javax.swing.JLabel();
        txtAutorApellido = new javax.swing.JTextField();
        chkAutorDesconocido = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txtDiaConsulta = new javax.swing.JTextField();
        txtMesConsulta = new javax.swing.JTextField();
        txtAnioConsulta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNombreSitioWeb = new javax.swing.JLabel();
        txtNombreSitio = new javax.swing.JTextField();
        panelGenerar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnAgregarAutor = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAutores = new javax.swing.JTable();
        chkOrganizacion = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrganizaciones = new javax.swing.JTable();
        btnLimpiarFormulario = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 50, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 600));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Generador de referencias APA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 33, 177, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Version 1.0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 52, 177, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UnADM");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 177, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DCEIT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 177, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 600));

        txtURL.setToolTipText("");
        txtURL.setName(""); // NOI18N
        getContentPane().add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 35, 500, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setText("Liga de internet");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("Título");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 135, 500, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setText("Fecha de publicacion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        txtAnioPublicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnioPublicacion.setName(""); // NOI18N
        txtAnioPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioPublicacionActionPerformed(evt);
            }
        });
        txtAnioPublicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioPublicacionKeyTyped(evt);
            }
        });
        getContentPane().add(txtAnioPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 50, -1));

        txtDiaPublicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaPublicacion.setName(""); // NOI18N
        txtDiaPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaPublicacionActionPerformed(evt);
            }
        });
        txtDiaPublicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaPublicacionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDiaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 25, -1));

        txtMesPublicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesPublicacion.setName(""); // NOI18N
        txtMesPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesPublicacionActionPerformed(evt);
            }
        });
        txtMesPublicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesPublicacionKeyTyped(evt);
            }
        });
        getContentPane().add(txtMesPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 25, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("(DD/MM/AAAA)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 80, -1));

        chkFechaDesconocida.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        chkFechaDesconocida.setText("Desconocida");
        chkFechaDesconocida.setToolTipText("");
        chkFechaDesconocida.setOpaque(false);
        chkFechaDesconocida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFechaDesconocidaActionPerformed(evt);
            }
        });
        getContentPane().add(chkFechaDesconocida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 378, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel9.setText("Agregar Autores");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, -1));
        getContentPane().add(txtOrganizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 187, 350, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setText("Iniciales");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 189, -1, -1));
        getContentPane().add(txtAutorIniciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 187, 90, -1));

        lblAutores.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblAutores.setText("Apellido");
        getContentPane().add(lblAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 189, -1, -1));
        getContentPane().add(txtAutorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 187, 170, -1));

        chkAutorDesconocido.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        chkAutorDesconocido.setText("Desconocidos");
        chkAutorDesconocido.setOpaque(false);
        getContentPane().add(chkAutorDesconocido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, 15));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel12.setText("Fecha de consulta");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 110, -1));

        txtDiaConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaConsulta.setName(""); // NOI18N
        txtDiaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaConsultaActionPerformed(evt);
            }
        });
        txtDiaConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaConsultaKeyTyped(evt);
            }
        });
        getContentPane().add(txtDiaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 25, -1));

        txtMesConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesConsulta.setName(""); // NOI18N
        txtMesConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesConsultaActionPerformed(evt);
            }
        });
        txtMesConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesConsultaKeyTyped(evt);
            }
        });
        getContentPane().add(txtMesConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 25, -1));

        txtAnioConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnioConsulta.setName(""); // NOI18N
        txtAnioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioConsultaActionPerformed(evt);
            }
        });
        txtAnioConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioConsultaKeyTyped(evt);
            }
        });
        getContentPane().add(txtAnioConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 50, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setText("(DD/MM/AAAA)");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 80, -1));

        txtNombreSitioWeb.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtNombreSitioWeb.setText("Nombre del sitio Web");
        getContentPane().add(txtNombreSitioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));
        getContentPane().add(txtNombreSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 85, 500, -1));

        panelGenerar.setBackground(new java.awt.Color(105, 28, 50));
        panelGenerar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelGenerarMouseMoved(evt);
            }
        });
        panelGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelGenerarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGenerarMousePressed(evt);
            }
        });
        panelGenerar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Generar Referencia");
        panelGenerar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, 110, -1));

        getContentPane().add(panelGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 130, 30));

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCerrar.setText("x");
        btnCerrar.setToolTipText("");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, 20));

        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtResultado.setLineWrap(true);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 500, -1));

        btnAgregarAutor.setBackground(new java.awt.Color(105, 28, 50));
        btnAgregarAutor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAgregarAutorMouseMoved(evt);
            }
        });
        btnAgregarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarAutorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarAutorMousePressed(evt);
            }
        });
        btnAgregarAutor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Agregar");
        btnAgregarAutor.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 3, 50, -1));

        getContentPane().add(btnAgregarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 186, 63, 20));

        tblAutores.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellido", "Iniciales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAutores.setRowHeight(14);
        tblAutores.getTableHeader().setResizingAllowed(false);
        tblAutores.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblAutores);
        if (tblAutores.getColumnModel().getColumnCount() > 0) {
            tblAutores.getColumnModel().getColumn(0).setResizable(false);
            tblAutores.getColumnModel().getColumn(1).setResizable(false);
            tblAutores.getColumnModel().getColumn(1).setHeaderValue("Iniciales");
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 212, 500, 70));

        chkOrganizacion.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        chkOrganizacion.setText("Organización");
        chkOrganizacion.setOpaque(false);
        chkOrganizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOrganizacionActionPerformed(evt);
            }
        });
        getContentPane().add(chkOrganizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 170, -1, 15));

        tblOrganizaciones.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblOrganizaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organización"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrganizaciones.setRowHeight(14);
        tblOrganizaciones.getTableHeader().setResizingAllowed(false);
        tblOrganizaciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblOrganizaciones);
        if (tblOrganizaciones.getColumnModel().getColumnCount() > 0) {
            tblOrganizaciones.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 500, 70));

        btnLimpiarFormulario.setBackground(new java.awt.Color(179, 142, 93));
        btnLimpiarFormulario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseMoved(evt);
            }
        });
        btnLimpiarFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMousePressed(evt);
            }
        });
        btnLimpiarFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Limpiar formulario");
        btnLimpiarFormulario.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, 110, -1));

        getContentPane().add(btnLimpiarFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioPublicacionActionPerformed

    private void txtDiaPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaPublicacionActionPerformed

    private void txtMesPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesPublicacionActionPerformed

    private void chkFechaDesconocidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFechaDesconocidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFechaDesconocidaActionPerformed

    private void txtDiaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaConsultaActionPerformed

    private void txtMesConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesConsultaActionPerformed

    private void txtAnioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioConsultaActionPerformed

    private void panelGenerarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGenerarMouseMoved
        panelGenerar.setBackground(new Color(157, 36, 73));
    }//GEN-LAST:event_panelGenerarMouseMoved

    private void panelGenerarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGenerarMouseExited
        panelGenerar.setBackground(new Color(105,28,50));
    }//GEN-LAST:event_panelGenerarMouseExited

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMousePressed

    private void panelGenerarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGenerarMousePressed
        if (datosValidos()) {
            Referencia ref = new Referencia();
            FechaConsulta fechaConsulta = 
                new FechaConsulta(
                    Integer.parseInt(txtDiaConsulta.getText().trim()),
                    Integer.parseInt(txtMesConsulta.getText().trim()), 
                    Integer.parseInt(txtAnioConsulta.getText().trim())
                );
            ref.setLigaWeb(txtURL.getText());
            ref.setTitulo(txtTitulo.getText());
            ref.setOrganizacionPagina(txtNombreSitio.getText());
            ref.setAutores(autores);
            ref.setOrganizaciones(organizaciones);
            ref.setAutorDesconocido(chkAutorDesconocido.isSelected());
            ref.setPublicacionDesconocida(chkFechaDesconocida.isSelected());
            if(!txtAnioPublicacion.getText().trim().equals("")) ref.setAnioPublicacion(Integer.parseInt(txtAnioPublicacion.getText()));
            if(!txtMesPublicacion.getText().trim().equals("")) ref.setMesPublicacion(Integer.parseInt(txtMesPublicacion.getText()));
            if(!txtDiaPublicacion.getText().trim().equals("")) ref.setDiaPublicacion(Integer.parseInt(txtDiaPublicacion.getText()));                
            ref.setConsulta(fechaConsulta);
            txtResultado.setText(ref.ObtenReferencia());
        }
    }//GEN-LAST:event_panelGenerarMousePressed

    private void txtDiaPublicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaPublicacionKeyTyped
        soloNumeros(evt, txtDiaPublicacion, 2);
    }//GEN-LAST:event_txtDiaPublicacionKeyTyped

    private void txtMesPublicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesPublicacionKeyTyped
        soloNumeros(evt, txtMesPublicacion, 2);
    }//GEN-LAST:event_txtMesPublicacionKeyTyped

    private void txtAnioPublicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioPublicacionKeyTyped
        soloNumeros(evt, txtAnioPublicacion, 4);
    }//GEN-LAST:event_txtAnioPublicacionKeyTyped

    private void txtDiaConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaConsultaKeyTyped
        soloNumeros(evt, txtDiaConsulta, 2);
    }//GEN-LAST:event_txtDiaConsultaKeyTyped

    private void txtMesConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesConsultaKeyTyped
        soloNumeros(evt, txtMesConsulta, 2);
    }//GEN-LAST:event_txtMesConsultaKeyTyped

    private void txtAnioConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioConsultaKeyTyped
        soloNumeros(evt, txtAnioConsulta, 4);
    }//GEN-LAST:event_txtAnioConsultaKeyTyped

    private void btnAgregarAutorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAutorMouseMoved
        btnAgregarAutor.setBackground(new Color(157, 36, 73));
    }//GEN-LAST:event_btnAgregarAutorMouseMoved

    private void btnAgregarAutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAutorMouseExited
        btnAgregarAutor.setBackground(new Color(105,28,50));
    }//GEN-LAST:event_btnAgregarAutorMouseExited

    private void btnAgregarAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAutorMousePressed
        if (!chkOrganizacion.isSelected()){
            if (txtAutorApellido.getText().trim().equals("")
            || txtAutorIniciales.getText().trim().equals("")){
                showMessageDialog(null, "Los datos del autor están vacíos!");
            } else {
                Autor a = new Autor(txtAutorApellido.getText().trim(), txtAutorIniciales.getText().trim());
                autores.add(a);
                String datos[] = {a.getApellido(), a.getIniciales()};
                tblModelAutor.addRow(datos);
                txtAutorApellido.setText("");
                txtAutorIniciales.setText("");
            }
        }else{
            if (txtOrganizacion.getText().trim().equals("")){
                showMessageDialog(null, "Los datos de la organización están vacíos!");
            }else{
                organizaciones = Arrays.copyOf(organizaciones, organizaciones.length + 1);
                organizaciones[organizaciones.length -1] = txtOrganizacion.getText().trim();
                String org[] = {organizaciones[organizaciones.length -1]};
                tblModelOrg.addRow(org);
                txtOrganizacion.setText("");
            }
        }
    }//GEN-LAST:event_btnAgregarAutorMousePressed

    private void chkOrganizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOrganizacionActionPerformed
        if(chkOrganizacion.isSelected()){
            lblAutores.setText("Organización");
            txtOrganizacion.setVisible(true);
            txtAutorApellido.setVisible(false);
            txtAutorIniciales.setVisible(false);
        } else {
            lblAutores.setText("Apellido");
            txtOrganizacion.setVisible(false);
            txtAutorApellido.setVisible(true);
            txtAutorIniciales.setVisible(true);            
        }
    }//GEN-LAST:event_chkOrganizacionActionPerformed

    private void btnLimpiarFormularioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseMoved
        btnLimpiarFormulario.setBackground(new Color(212, 193, 156));
    }//GEN-LAST:event_btnLimpiarFormularioMouseMoved

    private void btnLimpiarFormularioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseExited
        btnLimpiarFormulario.setBackground(new Color(179, 142, 93));
    }//GEN-LAST:event_btnLimpiarFormularioMouseExited

    private void btnLimpiarFormularioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMousePressed
        txtURL.setText("");
        txtNombreSitio.setText("");
        txtTitulo.setText("");
        txtAutorApellido.setText("");
        txtAutorIniciales.setText("");
        txtOrganizacion.setText("");
        txtDiaPublicacion.setText("");
        txtMesPublicacion.setText("");
        txtAnioPublicacion.setText("");
        txtResultado.setText("");
        
        chkAutorDesconocido.setSelected(false);
        chkOrganizacion.setSelected(false);
        chkFechaDesconocida.setSelected(false);
        
        tblModelAutor.setRowCount(0);
        tblModelOrg.setRowCount(0);
        
        autores.clear();
        organizaciones = new String[]{};
        
        setFechaConsultaHoy();
    }//GEN-LAST:event_btnLimpiarFormularioMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        _x = evt.getX();
        _y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - _x, y - _y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public boolean datosValidos(){
        boolean valido = true;
        String msg = "";
        
        if (txtURL.getText().trim().equals("")){
            msg += "- Liga de internet\n";
            valido = false;
        }
        if (txtNombreSitio.getText().trim().equals("")) {
            msg += "- Nombre del Sitio Web\n";
            valido = false;
        }
        if (txtTitulo.getText().trim().equals("")) {
            msg += "- Titulo\n";
            valido = false;
        }
        if(!chkFechaDesconocida.isSelected() && txtAnioPublicacion.getText().trim().equals("")){
            msg += "- Año de publicación\n";
            valido = false;
        }
        if(!valido){
            msg = "Los siguientes campos son requeridos:\n" + msg;
        }
        if ((txtDiaPublicacion.getText().trim().length() > 0 && Integer.parseInt(txtDiaPublicacion.getText().trim()) > 31)
        || (txtMesPublicacion.getText().trim().length() > 0 && Integer.parseInt(txtMesPublicacion.getText().trim()) > 12)){
            msg += "La fecha de publicación no parece ser válida!\n";
            valido = false;
        }
        if ((txtDiaConsulta.getText().trim().length() > 0 && Integer.parseInt(txtDiaConsulta.getText().trim()) > 31)
        || (txtMesConsulta.getText().trim().length() > 0 && Integer.parseInt(txtMesConsulta.getText().trim()) > 12)){
            msg += "La fecha de consulta no parece ser válida!\n";
            valido = false;
        }        
        if (!valido){
            showMessageDialog(null, msg);
        }
        return valido;
    }
    
    private void setFechaConsultaHoy(){
        Calendar hoy = Calendar.getInstance();
        var dia = String.valueOf(hoy.get(Calendar.DAY_OF_MONTH));
        var mes = String.valueOf(hoy.get(Calendar.MONTH) + 1);
        var anio = String.valueOf(hoy.get(Calendar.YEAR));
        // De forma predeterminada se hace el pre llenado de la fecha de consulta de hoy
        txtDiaConsulta.setText(dia);
        txtMesConsulta.setText(mes);
        txtAnioConsulta.setText(anio);
    }
    
    private void soloNumeros(java.awt.event.KeyEvent evt, javax.swing.JTextField tf, int maxchar){
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || tf.getText().length() >= maxchar){
            evt.consume();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregarAutor;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JPanel btnLimpiarFormulario;
    private javax.swing.JCheckBox chkAutorDesconocido;
    private javax.swing.JCheckBox chkFechaDesconocida;
    private javax.swing.JCheckBox chkOrganizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAutores;
    private javax.swing.JPanel panelGenerar;
    private javax.swing.JTable tblAutores;
    private javax.swing.JTable tblOrganizaciones;
    private javax.swing.JTextField txtAnioConsulta;
    private javax.swing.JTextField txtAnioPublicacion;
    private javax.swing.JTextField txtAutorApellido;
    private javax.swing.JTextField txtAutorIniciales;
    private javax.swing.JTextField txtDiaConsulta;
    private javax.swing.JTextField txtDiaPublicacion;
    private javax.swing.JTextField txtMesConsulta;
    private javax.swing.JTextField txtMesPublicacion;
    private javax.swing.JTextField txtNombreSitio;
    private javax.swing.JLabel txtNombreSitioWeb;
    private javax.swing.JTextField txtOrganizacion;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
